---
version: "3"
services:
  bun:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY:-a3cb7366ee8ca77225b4d41772e270e4e831d171d1de71d91707c42e7ba82cc9}
      - PORT=${PORT:-3000}